export let product = [
  {
    id: 1,
    title: "Iphone 13",
    description: "An apple mobile which is nothing like apple",
    price: 7000,
    discountPercenteng: 13000,
    rating: 4.8,
    stock: 94,
    brand: "Apple",
    category: "smartphone",
    thumbnail:
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-13-Midnight-frontimage",
    images: [
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-13-Midnight-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-13-Midnight-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-13-Midnight-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-13-Midnight-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-13-Midnight-frontimage",
    ],
  },
  {
    id: 2,
    title: "Iphone x",
    description: "An apple mobile which is nothing like apple",
    price: 3000,
    discountPercenteng: 5000,
    rating: 4.3,
    stock: 80,
    brand: "Apple",
    category: "smartphone",
    thumbnail:
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-15-Pink-frontimage",
    images: [
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-15-Pink-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-15-Pink-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-15-Pink-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-15-Pink-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-15-Pink-frontimage",
    ],
  },
  {
    id: 3,
    title: "Galaxy S24 Ultra",
    description: "An samsung mobile which is nothing like samsung",
    price: 10000,
    discountPercenteng: 15000,
    rating: 4.8,
    stock: 94,
    brand: "Samsung",
    category: "smartphone",
    thumbnail:
      "https://t-mobile.scene7.com/is/image/Tmusprod/Samsung-Galaxy-S24-Ultra-Titanium-Gray-frontimage",
    images: [
      "https://t-mobile.scene7.com/is/image/Tmusprod/Samsung-Galaxy-S24-Ultra-Titanium-Gray-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Samsung-Galaxy-S24-Ultra-Titanium-Gray-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Samsung-Galaxy-S24-Ultra-Titanium-Gray-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Samsung-Galaxy-S24-Ultra-Titanium-Gray-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Samsung-Galaxy-S24-Ultra-Titanium-Gray-frontimage",
    ],
  },
  {
    id: 4,
    title: "Galaxy Z Fold5",
    description: "An apple samsung which is nothing like samsung",
    price: 7000,
    discountPercenteng: 13000,
    rating: 4.8,
    stock: 94,
    brand: "Samsung",
    category: "smartphone",
    thumbnail:
      "https://t-mobile.scene7.com/is/image/Tmusprod/Samsung-Galaxy-Z-Fold5-Phantom-Black-frontimage",
    images: [
      "https://t-mobile.scene7.com/is/image/Tmusprod/Samsung-Galaxy-Z-Fold5-Phantom-Black-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Samsung-Galaxy-Z-Fold5-Phantom-Black-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Samsung-Galaxy-Z-Fold5-Phantom-Black-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Samsung-Galaxy-Z-Fold5-Phantom-Black-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Samsung-Galaxy-Z-Fold5-Phantom-Black-frontimage",
    ],
  },
  {
    id: 5,
    title: "Galaxy A15 5G",
    description: "An apple samsung which is nothing like samsung",
    price: 4000,
    discountPercenteng: 6000,
    rating: 4.8,
    stock: 94,
    brand: "Samsung",
    category: "smartphone",
    thumbnail:
      "https://t-mobile.scene7.com/is/image/Tmusprod/Samsung-Galaxy-A15-5G-Blue-Black-frontimage",
    images: [
      "https://t-mobile.scene7.com/is/image/Tmusprod/Samsung-Galaxy-A15-5G-Blue-Black-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Samsung-Galaxy-A15-5G-Blue-Black-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Samsung-Galaxy-A15-5G-Blue-Black-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Samsung-Galaxy-A15-5G-Blue-Black-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Samsung-Galaxy-A15-5G-Blue-Black-frontimage",
    ],
  },
  {
    id: 6,
    title: "Pixel 8 Pro",
    description: "An Pixel mobile which is nothing like Pixel",
    price: 7000,
    discountPercenteng: 13000,
    rating: 4.8,
    stock: 94,
    brand: "Pixel",
    category: "smartphone",
    thumbnail:
      "https://t-mobile.scene7.com/is/image/Tmusprod/Google-Pixel-8-Pro-Obsidian-frontimage",
    images: [
      "https://t-mobile.scene7.com/is/image/Tmusprod/Google-Pixel-8-Pro-Obsidian-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Google-Pixel-8-Pro-Obsidian-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Google-Pixel-8-Pro-Obsidian-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Google-Pixel-8-Pro-Obsidian-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Google-Pixel-8-Pro-Obsidian-frontimage",
    ],
  },
  {
    id: 7,
    title: "Iphone 13",
    description: "An apple mobile which is nothing like apple",
    price: 7000,
    discountPercenteng: 13000,
    rating: 4.8,
    stock: 94,
    brand: "Apple",
    category: "smartphone",
    thumbnail:
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-13-Midnight-frontimage",
    images: [
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-13-Midnight-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-13-Midnight-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-13-Midnight-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-13-Midnight-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-13-Midnight-frontimage",
    ],
  },
  {
    id: 8,
    title: "iPhone SE (3rd gen)",
    description: "An apple mobile which is nothing like apple",
    price: 5000,
    discountPercenteng: 7000,
    rating: 4.8,
    stock: 94,
    brand: "Apple",
    category: "smartphone",
    thumbnail:
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-SE-3rd-gen-Starlight-frontimage",
    images: [
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-SE-3rd-gen-Starlight-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-SE-3rd-gen-Starlight-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-SE-3rd-gen-Starlight-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-SE-3rd-gen-Starlight-frontimage",
      "https://t-mobile.scene7.com/is/image/Tmusprod/Apple-iPhone-SE-3rd-gen-Starlight-frontimage",
    ],
  },
];
